### PR TITLE
Allow boundless coordinates for bilinear and nearest regridders

### PR DESCRIPTION
**Pull request by stephenworsley**
The bilinear and nearest methods do not require coordinate bounds in order for ESMF to do regridding. This PR makes it so that grids without bound information are regridable via these methods.

### CODE REVIEW

**Comment by ESadek-MO** [comment]
@pp-mo

**Comment by bouweandela** [comment]
It would be great if this could get reviewed and merged for reasons explained in https://github.com/SciTools-incubator/iris-esmf-regrid/issues/368#issuecomment-2178488893. Would it help to speed this up if I did a review?

**Comment by pp-mo** [comment]
@stephenworsley please update + I will progress !

**Review by HGWright — APPROVED** [review]
Looks great @stephenworsley, thanks for this change! Been in the works for a while.

**Pull request merged**
